[build]
  # We run the build from the root directory to avoid Netlify base directory duplication issues
  command = "cd frontend && npm install && npm run build"
  
  # The output folder is explicitly defined from the root
  publish = "frontend/dist/client"

[[redirects]]
  # Redirect all unknown requests to index.html to allow TanStack Router to handle routing
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://pssf-operations-centre.onrender.com"
