/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelfServiceRouteImport } from './routes/self-service'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as HrErpRouteImport } from './routes/hr-erp'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as EmployeePerformanceRouteImport } from './routes/employee-performance'
import { Route as ContributionsRouteImport } from './routes/contributions'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as BenefitsRouteImport } from './routes/benefits'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as IndexRouteImport } from './routes/index'

const SelfServiceRoute = SelfServiceRouteImport.update({
  id: '/self-service',
  path: '/self-service',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const HrErpRoute = HrErpRouteImport.update({
  id: '/hr-erp',
  path: '/hr-erp',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeePerformanceRoute = EmployeePerformanceRouteImport.update({
  id: '/employee-performance',
  path: '/employee-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributionsRoute = ContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsRoute = BenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/analytics': typeof AnalyticsRoute
  '/benefits': typeof BenefitsRoute
  '/claims': typeof ClaimsRoute
  '/contributions': typeof ContributionsRoute
  '/employee-performance': typeof EmployeePerformanceRoute
  '/finance': typeof FinanceRoute
  '/hr-erp': typeof HrErpRoute
  '/membership': typeof MembershipRoute
  '/outreach': typeof OutreachRoute
  '/self-service': typeof SelfServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/analytics': typeof AnalyticsRoute
  '/benefits': typeof BenefitsRoute
  '/claims': typeof ClaimsRoute
  '/contributions': typeof ContributionsRoute
  '/employee-performance': typeof EmployeePerformanceRoute
  '/finance': typeof FinanceRoute
  '/hr-erp': typeof HrErpRoute
  '/membership': typeof MembershipRoute
  '/outreach': typeof OutreachRoute
  '/self-service': typeof SelfServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/analytics': typeof AnalyticsRoute
  '/benefits': typeof BenefitsRoute
  '/claims': typeof ClaimsRoute
  '/contributions': typeof ContributionsRoute
  '/employee-performance': typeof EmployeePerformanceRoute
  '/finance': typeof FinanceRoute
  '/hr-erp': typeof HrErpRoute
  '/membership': typeof MembershipRoute
  '/outreach': typeof OutreachRoute
  '/self-service': typeof SelfServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administration'
    | '/analytics'
    | '/benefits'
    | '/claims'
    | '/contributions'
    | '/employee-performance'
    | '/finance'
    | '/hr-erp'
    | '/membership'
    | '/outreach'
    | '/self-service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administration'
    | '/analytics'
    | '/benefits'
    | '/claims'
    | '/contributions'
    | '/employee-performance'
    | '/finance'
    | '/hr-erp'
    | '/membership'
    | '/outreach'
    | '/self-service'
  id:
    | '__root__'
    | '/'
    | '/administration'
    | '/analytics'
    | '/benefits'
    | '/claims'
    | '/contributions'
    | '/employee-performance'
    | '/finance'
    | '/hr-erp'
    | '/membership'
    | '/outreach'
    | '/self-service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrationRoute: typeof AdministrationRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BenefitsRoute: typeof BenefitsRoute
  ClaimsRoute: typeof ClaimsRoute
  ContributionsRoute: typeof ContributionsRoute
  EmployeePerformanceRoute: typeof EmployeePerformanceRoute
  FinanceRoute: typeof FinanceRoute
  HrErpRoute: typeof HrErpRoute
  MembershipRoute: typeof MembershipRoute
  OutreachRoute: typeof OutreachRoute
  SelfServiceRoute: typeof SelfServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/self-service': {
      id: '/self-service'
      path: '/self-service'
      fullPath: '/self-service'
      preLoaderRoute: typeof SelfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-erp': {
      id: '/hr-erp'
      path: '/hr-erp'
      fullPath: '/hr-erp'
      preLoaderRoute: typeof HrErpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-performance': {
      id: '/employee-performance'
      path: '/employee-performance'
      fullPath: '/employee-performance'
      preLoaderRoute: typeof EmployeePerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributions': {
      id: '/contributions'
      path: '/contributions'
      fullPath: '/contributions'
      preLoaderRoute: typeof ContributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits': {
      id: '/benefits'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof BenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrationRoute: AdministrationRoute,
  AnalyticsRoute: AnalyticsRoute,
  BenefitsRoute: BenefitsRoute,
  ClaimsRoute: ClaimsRoute,
  ContributionsRoute: ContributionsRoute,
  EmployeePerformanceRoute: EmployeePerformanceRoute,
  FinanceRoute: FinanceRoute,
  HrErpRoute: HrErpRoute,
  MembershipRoute: MembershipRoute,
  OutreachRoute: OutreachRoute,
  SelfServiceRoute: SelfServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
